# Generated by Django 3.1.7 on 2021-03-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(null=True)),
                ('due_on', models.DateField(null=True)),
                ('owner', models.CharField(max_length=50)),
                ('mark', models.BooleanField(null=True)),
                ('todos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
