# Generated by Django 3.1.7 on 2021-03-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='mark',
            field=models.BooleanField(null=True),
        ),
    ]
